version: "0.1.0 #{build}"

platform:
  - x64

cache:
  - node_modules
  - '%APPDATA%\npm-cache'
  - '%USERPROFILE%\.electron'

image: Visual Studio 2017

init:
  - git config --global core.autocrlf input

install:
  - git reset --hard HEAD
  - npm install npm -g
  - npm install
  - npm prune

build_script:
  - node --version
  - npm --version
  - npm run-script build

test: off
